### ISSUE TITLE
Any changes prior to publishing the code on github

### ISSUE THREAD

**Issue by sniperrifle2004** [TwitchPlaysPokemon/vba-rr#3]
So I am going to try and fix the linux build for this, but to do that I suspect the history of the google code project will be invaluable. For this purpose I have exported that project to https://github.com/sniperrifle2004/vba-rerecording. Now I have cherry-picked the changes you made while the project lived on github, but I need to know for sure that no other changes were made before that. I have used git diff to check and it does not appear to be the case, but I would like to know for sure.

**Comment by Felk** [comment]
AFAIK we did not modify the code before committing it to github. It supposedly is the same version 23.5 code available on google code. I'm requesting second confirmation from @ProjectRevoTPP though, as he did the commit

**Comment by PikalaxALT** [comment]
As far as I know, all our modifications are based on the v7 engine, as the v8 engine has additional problems handling Pokemon Crystal which we were unable to resolve on our own.  These modifications include:
1. Reporting of the WRAM bank state to FF70, such that it can be read by Lua scripting.  The display value of FF70 is not entirely accurate (BGB, a far more accurate DMG/CGB emulator, shows the higher 5 bits as constitutively set, which affects read operations), but for our purposes it's close enough.
2. Fixed the issue where the RTC is not correctly written to the save file, resulting in generation 2 Pokemon games not being able to find this data on save load.

**Comment by RevoSucks** [comment]
three: We changed the icon to tppPc, but other than that, its pretty much unmodified. Oh, felk did some .sln hacks to get it to load in Visual Studio, but that's it.

Go nuts, we can remerge those small changes anyway.

**Comment by Felk** [comment]
Might be worth mentioning that I have no idea what I was doing when I tried to get it to compile with VS2015. I changed some settings and removed the manifest file and it works, I don't understand manifest files and what they are needed for.

If you managed to get the code to build on VS2015 in a way where you actually knew what you were doing, I suggest not merging this commit: https://github.com/TwitchPlaysPokemon/vba-rr/commit/234aabfc9a762ce967051d7307d17782dde96161

**Comment by sniperrifle2004** [comment]
Thanks for all the information!

Now I can continue the work with one worry less :)

@Felk With regards to visual studio I am as much in the dark as (or more in the dark than) you are so I am just going to assume that what you did is exactly right. If not I will cross that bridge when I get there. Since I am mainly going to focus on getting the linux build working and running properly that will likely take a while. Probably when I have to start verifying that I am not breaking the windows build.

**Comment by sniperrifle2004** [comment]
![sdlbuildrunning](https://cloud.githubusercontent.com/assets/18223222/14379418/28ad9544-fd7a-11e5-921e-7e8772fc85a9.png) PogChamp
