### ISSUE TITLE
What are some of the issues you have found?

### ISSUE THREAD

**Issue by sniperrifle2004** [TwitchPlaysPokemon/vba-rr#4]
So since you have been working with vba-rr for quite some time (Well at least longer than I have) I could use your help. I would really appreciate it if you could create some issues for any issues you encounter(ed) at https://github.com/sniperrifle2004/vba-rerecording . Please mention the core version (Not the vba-rr version since that is pretty much useless without knowing the exact combination of cores) and any other information that may be useful. I really need as much information as possible for https://github.com/sniperrifle2004/vba-rerecording/issues/105 since the current situation is a maintenance nightmare. Other than that I am happy to report that the linux SDL build is working again (The GTK build is a work in progress) and I have just verified that the windows build is still functioning properly too.

Thank you in advance!

**Comment by PikalaxALT** [comment]
V7 core: cheat codes don't seem to work with GB/C games.  (These are manually-created codes of the format `dbbw $1, value, address`, which work on other emulators).  GBA codes do work on their respective games

**Comment by RevoSucks** [comment]
V8 core: Inaccurate bank switching, leads to slight graphical corruption on Pokemon Crystal especially and Pokemon Fire Red minor. Other games may be affected.

**Comment by PikalaxALT** [comment]
@ProjectRevoTPP Those are two completely different problems.  One is with GB/C WRAM banking, the other is undiagnosed GBA.

**Comment by sniperrifle2004** [comment]
I could use a little more information on that WRAM banking issue. I see no difference in behavior in regard to the banking itself. However there are some non trivial changes surrounding HDMA and memory accessibility which could lead to graphical glitches as well. What led you to believe it was a banking issue?

**Comment by sniperrifle2004** [comment]
I fixed the crystal graphical glitch issue. It had nothing to do with bank switching though. Core V8 of my current master should thus hopefully be suitable for crystal anniversary edition. I will preemptively look into the visibility of the selected wram bank and the other registers for the custom AI.

**Comment by sniperrifle2004** [comment]
I am closing this for now. Thank you for the information. If you find any other issues please report them to https://github.com/vba-rerecording/vba-rerecording/issues
